### ISSUE TITLE
error in alarm display: fake alarms

### ISSUE THREAD

**Issue by xynher** [crdroidandroid/android_packages_apps_DeskClock#5]
crdroid 10.2
Poco X3 NFC / surya

----------- Description:----------
Some fake alarms are being displayed:

The alarm time at lockscreen is incorrect, it counts up automaticly (time+ 10 minutes) (21:52 in the screenshot) and stops at full hour. Then again time+10.
![1000012394](https://github.com/crdroidandroid/android_packages_apps_DeskClock/assets/32439350/7a43c5c6-7dd4-4844-8f45-d520c3401242)

in the widget its fixed at next full hour:
![1000012393](https://github.com/crdroidandroid/android_packages_apps_DeskClock/assets/32439350/cf46679f-6650-46cd-9db6-6aadf478eda3)

the extended statusbar icon shows full hour as well, no notifications appear for these fake alarms.

It doesn't matter wether an real alarm is set or not, these alarms wont go away.

---------------Reproduce-----------
Setting up the phone: changing settings in the Settings app.  The error has now occurred for the third time after I set up a fresh system.  It is unknown which setting exactly causes this error.

**Comment by gwolf2u** [comment]
use issue tracker
